### ISSUE TITLE
Doesn't seem to see the files when referenced without underscore at beginning + file extension.

### ISSUE THREAD

**Issue by fabm22** [at-import/node-sass-import-once#25]
Hi, I am using a simple gulp-sass task while using node-sass-import-once, and as soon as I reference in one of my .scss files a @import  of a file without  _xxxx.scss (underscore + file extension), it fails to find it... 

```
var sass = require('gulp-sass'),
    nodeSass = require('node-sass'),
    importOnce = require('node-sass-import-once')


gulp.task('sass', function () {

    return gulp.src(CONFIG.scss + '**/*.{scss,sass}')
        .pipe(sass({includePaths: CONFIG.importPath, importer: importOnce}).on('error', sass.logError))
        .pipe(gulp.dest(CONFIG.app + 'assets/style'));
});
```

```
@import '../../app/components/layout/container/container.ui-layout';

Error: Could not import `../../app/components/layout/container/container.ui-layout` from any of the following locations:
  /Users/user/projects/project/src/main/webapp/app/components/layout/container/container.ui-layout
  /Users/user/projects/project/src/main/webapp/app/components/layout/container/container.ui-layout
  /Users/user/projects/project/src/main/app/components/layout/container/container.ui-layout
```

It specifically needs to be explicited by specifying underscore + extension to work, like in

```
@import '../../app/components/layout/container/_container.ui-layout.scss';
```

Is this the desired behaviour ?

**Comment by jonhurrell** [comment]
Just hit this same issue now.

**Comment by Snugug** [comment]
Was this resolved by https://github.com/at-import/node-sass-import-once/pull/26?

**Comment by jonhurrell** [comment]
Issue persists for me.

**Comment by krsteyn** [comment]
Hi I see that the npm package has not been updated yet so I still get this problem.  When will this fix be pushed in a release?  Will include the dependency directly from github for now to work around this and see if that resolves the problem.
